### PR TITLE
Share

### PR DESCRIPTION
**Pull request by FedericoDiTosto**
I have added a modal that allows the url of the site to be shared via various social media. The modal is responsive (top for large devices, bottom for mobile).

### CODE REVIEW

**Comment by AlasdairMott** [comment]
Looks great! Its much clearer than the current approach. Love the on screen feedback 

I'd like it to act like a modal similar to the help screen. 
Some ideas - 

This one is pretty standard. It should take 100% width and height - clicking anywhere outside of the rectangle would just close it.
image

This one blurs the background... might be clearer that its a modal over the whole workspace.
image

Closest to the existing help modal, but might be going too far.
image

I think I like number 2 the most... but I might want to update the help modal to match the same design language.

**Comment by FedericoDiTosto** [comment]
really nice, definitely more consistent with the design style used, I also agree with #2. do you want me to fix the help modal as well?

**Comment by FedericoDiTosto** [comment]
modified the Share Modal & the Help Modal both with the same design language

additional idea: (I have no idea how to do this) add an image that is a screenshot of the Canvas to use as a preview image for sharing the url

**Comment by AlasdairMott** [comment]
Oh thats perfect! Thanks so much.

> add an image that is a screenshot of the Canvas to use as a preview image for sharing the url

yeah that would be really cool. I don't know either haha. [This post](https://github.com/pmndrs/react-three-fiber/discussions/2054)  explains how to screenshot in r3f. [Attaching to the link](https://andrejgajdos.com/how-to-create-a-link-preview/) sound harder. That can be a separate PR if you like though

**Pull request merged**
